#!/system/bin/sh
echo "============= PACEfied Bluetooth Volume Boost ==============="
if [ `busybox id -u` -ne 0 ]; then echo "Must be root!"; exit 1; fi
content insert --uri content://settings/system --bind value:s:15 --bind name:s:volume_music_bt_a2dp
echo "Done, now rebooting"
reboot


